application: nestiqapi
version: main
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

builtins:
- deferred: on

inbound_services:
- warmup
